import fs from 'fs';
import path from 'path';

// Usage: node generate_golden.js <CONCEPT_ID> <RULE_ID> "Example Clause Text"

const [,, conceptId, ruleId, clauseText] = process.argv;

if (!conceptId || !ruleId || !clauseText) {
    console.error("Usage: node generate_golden.js <CONCEPT_ID> <RULE_ID> 'Example Clause Text'");
    process.exit(1);
}

const template = `/**
 * Golden Test for ${ruleId} related to ${conceptId}
 * Generated by Ontology Builder
 */

import { executePipeline } from '../../assets/js/engine/Trothix.js';
import assert from 'assert';

async function runTest() {
    console.log("Running Golden Test for ${ruleId}...");
    const text = "${clauseText.replace(/"/g, '\\"')}";
    
    const result = await executePipeline(text, { documentType: "Generic" });
    
    // Assert finding exists
    const finding = result.findings.find(f => f.rule === '${ruleId}');
    assert.ok(finding, "Expected to find rule ${ruleId} in findings");
    
    console.log("✅ Golden Test Passed.");
}

runTest().catch(err => {
    console.error("❌ Golden Test Failed:", err.message);
    process.exit(1);
});
`;

const testFilename = path.join(process.cwd(), 'tests', 'golden', `${ruleId.toLowerCase()}.test.js`);
const testDir = path.dirname(testFilename);
if (!fs.existsSync(testDir)) {
    fs.mkdirSync(testDir, { recursive: true });
}

fs.writeFileSync(testFilename, template);
console.log(`Generated Golden Test: ${testFilename}`);
